services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: gerencia
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: spring_container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - springnet

volumes:
  mysql_data:

networks:
  springnet:
