services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: gerencia
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
    networks:
      - springnet
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    image: bmespantalho29/gestaofinanceira:latest
    ports:
      - "8080:8080"
    networks:
      - springnet

volumes:
  mysql_data:

networks:
  springnet:
